name: Check Markdown links

on:
    workflow_dispatch:

permissions: {}

jobs:
    markdown-link-check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3
            - uses: gaurav-nelson/github-action-markdown-link-check@v1
              with:
                  use-quiet-mode: 'no'
                  use-verbose-mode: 'yes'
                  folder-path: '., ./docs'
                  max-depth: -1
                  config-file: '.github/workflows/check-doc-links-config.json'
