name: Install and Build (Reusable)
on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        default: ./
        type: string

jobs:
  cache-deps:
    name: Cache Deps
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency caching
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/composer/files
          key: ${{ runner.os }}-smoke-test-release-${{ secrets.WORKFLOW_CACHE }}-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install pnpm -g

      - name: Install NPM and install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: pnpm install

      - name: Install Composer
        working-directory: ${{ inputs.working_directory }}
        run: composer install

      - name: list directory after install
        run: ls -laR ~/