name: Install and Build (Reusable)
on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        default: ./
        type: string
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-deps:
    name: Cache Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency caching
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.pnpm-store
            ~/.local/share/pnpm/store
            ~/.cache/composer/files
          key: ${{ runner.os }}-smoke-test-release-2-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install pnpm -g

      - name: Install NPM and install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: pnpm install

      - name: Install Composer
        working-directory: ${{ inputs.working_directory }}/plugins/woocommerce
        run: composer install

      - name: Install Composer sub
        working-directory: ${{ inputs.working_directory }}/plugins/woocommerce/sub
        run: composer install

      - name: list directory after install
        run: ls -laR ~/