name: Install and Build (Reusable)
on:
  workflow_call:
    cache-deps:
        name: Cache Deps
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.7.0
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache modules
              id: cache-modules
              uses: actions/cache@v3
              with:
                path: |
                  plugins/woocommerce/node_modules
                  plugins/woocommerce/vendor
                key: ${{ runner.os }}-build-${{ hashFiles('plugins/woocommerce/package-lock.json', 'plugins/woocommerce/composer.lock') }}

            - name: Install NPM and install dependencies
              working-directory: plugins/woocommerce
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: Install Composer
              working-directory: plugins/woocommerce
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: composer install
