name: Add reply to fill template.
on:
  issues:
    types:
      - labeled
jobs:
  fill-template-comment:
    if: "github.event.label.name == 'needs: template'"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add reply to fill template
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hi @${{ github.event.issue.user.login }},\n\n\
              Thank you for submitting the issue. However, you didn't fill out the details of the bug report template that we ask for. Without these details, we can't fully evaluate this issue. Please provide us with the information requested so we could take a look further."
            }) 