name: Run post release processes
on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog-in-trunk:
    name: Update changelog in trunk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get tag name
        id: tag
        uses: actions/github-script@v6
        with:
          script: |
            const tag = ${{ toJSON( github.event.release.tag_name ) }}

            console.log( `::set-output name=tag::release/${ tag.substring( 0, 3 ) }` )

      - name: Git fetch the release branch
        run: git fetch origin ${{ steps.tag.outputs.tag }}

      - name: Switch to release branch
        run: git checkout ${{ steps.tag.outputs.tag }}

      - name: Copy changelog.txt contents to env variable
        run: export CHANGELOG=$(cat changelog.txt)

      - name: Check var
        run: echo $CHANGELOG
