name: Run post release processes
on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog-in-trunk:
    name: Update changelog in trunk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get tag name
        id: tag
        uses: actions/github-script@v6
        with:
          script: |
            const tag = ${{ toJSON( github.event.release.tag_name ) }}

            console.log( `::set-output name=tag::release/${ tag.substring( 0, 3 ) }` )

      - name: debug:check origin branch
        run: git rev-parse --abbrev-ref HEAD

      - name: debug:check origin changelog.txt
        run: cat changelog.txt

      - name: Git fetch the release branch
        run: git fetch origin main

      - name: Copy changelog.txt to vm root
        run: cp changelog.txt ../../changelog.txt

      - name: Switch to trunk branch
        run: git checkout main
      
      - name: Create a new branch based on trunk
        run: git checkout -b update/changelog-from-release

      - name: Copy saved changelog.txt to monorepo
        run: cp ../../changelog.txt ./changelog.txt

      - name: check new changelog
        run: cat ./changelog.txt
