name: Build
on:
  push:
    branches: ["trunk", "main"]
  workflow_dispatch:
jobs:
  next:
    name: Next step
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  runbuild:
    name: Run Build
    uses: ./.github/workflows/install-build.yml
    # with:
    #   working_directory: plugins/woocommerce
