name: Build
on: push
jobs:
  runbuild:
    name: Run Build
    uses: ./.github/workflows/install-build.yml
    with:
      working_directory: plugins/woocommerce

  next:
    name: Next step
    runs-on: ubuntu-latest
    needs: [runbuild]
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Restore Cache modules
          uses: actions/cache@v3
          with:
            path: |
              **/node_modules
              **/vendor
            key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json', '**/composer.lock') }}

        - name: find it
          run: ls -R
