name: Build
on: push
jobs:
    cache-deps:
        name: Cache Deps
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.7.0
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache modules
              id: cache-modules
              uses: actions/cache@v3
              env:
                cache-name: cache-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: |
                  plugin/woocommerce/node_modules
                  plugin/woocommerce/vendor
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('plugins/woocommerce/package-lock.json') }}-${{ hashFiles('plugins/woocommerce/composer.lock') }}

            - name: Install NPM and install dependencies
              working-directory: plugins/woocommerce
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: Install Composer
              working-directory: plugins/woocommerce
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: composer install

            - name: find it
              run: ls -R
    next:
      name: Next step
      runs-on: ubuntu-latest
      needs: [cache-deps]
      steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Cache modules
            uses: actions/cache@v3
            with:
              # npm cache files are stored in `~/.npm` on Linux/macOS
              path: |
                plugin/woocommerce/node_modules
                plugin/woocommerce/vendor
              key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('plugins/woocommerce/package-lock.json') }}-${{ hashFiles('plugins/woocommerce/composer.lock') }}

          - name: find it
            run: ls -R
