name: Build
on: push
jobs:
    build:
        name: Build app
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.7.0
              with:
                  access_token: ${{ github.token }}

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install NPM and install dependencies
              run: npm install

            - name: Install Composer
              run: composer install