name: Build
on: push
jobs:
  runbuild:
    name: Run Build
    uses: ./.github/workflows/install-build.yml
    with:
      working_directory: plugins/woocommerce

  next:
    name: Next step
    runs-on: ubuntu-latest
    needs: [runbuild]
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Cache modules
          uses: actions/cache@v3
          with:
            path: |
              plugins/woocommerce/node_modules
              plugins/woocommerce/vendor
            key: ${{ runner.os }}-build-${{ hashFiles('plugins/woocommerce/package-lock.json', 'plugins/woocommerce/composer.lock') }}

        - name: find it
          run: ls -R
