name: Push Runs
on: push
jobs:
    do-it:
      name: Do it
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Cache modules
            uses: actions/cache@v3
            with:
              path: |
                **/node_modules
                **/vendor
              key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json', '**/composer.lock') }}

          - name: find it second
            run: ls -R
