name: Build
on:
  push:
    branches: ["trunk", "main"]
  workflow_dispatch:
jobs:
  slack:
    runs-on: ubuntu-20.04
    steps:
      - name: GH
        uses: actions/github-script@v6
        id: gh
        with:
          script: |
            async function run() {
              return await github.rest.repos.getLatestRelease({
                owner: 'woocommerce',
                repo: 'woocommerce'
              });
            }
            run().then( (version) => {
              console.log(version.data.tag_name);
              version = parseFloat( version.data.tag_name ) + 0.1;
              version = version.toPrecision( 2 );
              let next_version = parseFloat( version.data.tag_name ) + 0.2;
              next_version = version.toPrecision( 2 );
              return { "version": version, "next_version": next_version };
            });
      - name: Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
         slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
         slack-channel: GQYA0M7JQ
         slack-text: ":warning-8c: ${{steps.gh.outputs.result.version}} Code Freeze :ice_cube:
The automation to cut the release branch for ${{steps.gh.outputs.result.version}} has run. Any PRs that were not already merged will be a part of ${{steps.gh.outputs.result.next_version}} by default. If you have something that needs to make ${{steps.gh.outputs.result.version}} that hasn't yet been merged, please see the fieldguide page for the code freeze: https://fieldguide.automattic.com/code-freeze-for-woocommerce-core-release/."