name: Test permissions
permissions: {}

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: cache
        run: mkdir caching && cd caching && touch file.log

      - name: Cache Composer Dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: caching
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}-composer-