name: Test permissions
permissions: {}

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: build
        run: touch hello.log

      - name: Upload the zip file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: woocommerce
          path: ./
          retention-days: 7
          