name: Test permissions
permissions: {}

on:
  - push
  - pull_request

jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Setup Node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          registry-url: 'https://registry.npmjs.org'
