name: Test permissions
permissions: {}

on:
  - push
  - pull_request

jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: phpcs, sirbrillig/phpcs-changed
