name: Add Triage Label

on:
  issues:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-20.04
    steps:
      - uses: andymckay/labeler@master
        if: github.event.issue.labels[0] == null
        with:
          add-labels: 'status: awaiting triage'
          ignore-if-assigned: true
          ignore-if-labeled: true
